services:
    nginx:
        image: "nginx:1.26-alpine"
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/laravel
        networks:
            - soundhead
        depends_on:
            - php

    php:
        build:
            context: docker
            dockerfile: php.Dockerfile
        user: ${DOCKER_USER}
        volumes:
            - .:/var/www/laravel
        networks:
            - soundhead
        depends_on:
            - redis
            - postgres

    lara:
        build:
            context: docker
            dockerfile: php.Dockerfile
        user: ${DOCKER_USER}
        ports:
            - 80:8000
        volumes:
            - .:/var/www/laravel
            - ./storage/app/public:/var/www/laravel/public/storage
        command: php artisan serve --host=0.0.0.0
        networks:
            - soundhead
        depends_on:
            - redis
            - postgres

    composer:
        image: composer:2.7.4
        user: ${DOCKER_USER}
        volumes:
            - .:/var/www/laravel
        working_dir: /var/www/laravel
        entrypoint: ["composer", "--ignore-platform-reqs"]

    artisan:
        build:
            context: docker
            dockerfile: php.Dockerfile
        user: ${DOCKER_USER}
        volumes:
            - .:/var/www/laravel
        entrypoint: ["php", "artisan"]
        networks:
            - soundhead
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:6.0.20-alpine
        user: ${DOCKER_USER}
        networks:
            - soundhead

    postgres:
        image: postgres:14.11-alpine
        environment:
            - POSTGRES_DB=soundhead
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker/tmp-postgres:/var/lib/postgresql/data
        networks:
            - soundhead

networks:
    soundhead:
        external: true
