services:
    nginx:
        image: "nginx:1.26-alpine"
        ports:
            - "80:80"
        environment:
            - MAIN_PAGE_PROXY_TO=http://nuxt:3000
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
            - .:/var/www/laravel
        # команда envsubst используется для подстановки переменных окружения в конфиг nginx
        command: sh -c "envsubst '$${MAIN_PAGE_PROXY_TO}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        networks:
            - soundhead
        depends_on:
            - php

    back:
        image: "nginx:1.26-alpine"
        ports:
            - "80:80"
        environment:
            - MAIN_PAGE_PROXY_TO=http://localhost/api/docs
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
            - .:/var/www/laravel
        command: sh -c "envsubst '$${MAIN_PAGE_PROXY_TO}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        networks:
            - soundhead
        depends_on:
            - php

    php:
        build:
            context: docker
            dockerfile: php.Dockerfile
        user: ${DOCKER_USER:-1000:1000}
        volumes:
            - .:/var/www/laravel
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_TRIGGER: yes
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - soundhead
        depends_on:
            - redis
            - postgres

    composer:
        image: composer:2.7.4
        user: ${DOCKER_USER:-1000:1000}
        volumes:
            - .:/var/www/laravel
        working_dir: /var/www/laravel
        entrypoint: ["composer", "--ignore-platform-reqs"]

    artisan:
        build:
            context: docker
            dockerfile: php.Dockerfile
        user: ${DOCKER_USER:-1000:1000}
        volumes:
            - .:/var/www/laravel
        entrypoint: ["php", "artisan"]
        networks:
            - soundhead
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:6.0.20-alpine
        networks:
            - soundhead

    postgres:
        image: postgres:14.11-alpine
        environment:
            - POSTGRES_DB=soundhead
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker/tmp-postgres:/var/lib/postgresql/data
        networks:
            - soundhead

networks:
    soundhead:
        external: true
