name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  Deploy-dev:
    runs-on: ubuntu-22.04
    environment:
      name: ribov
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_IP }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          script: |
            cd ${{ vars.LOCATION_BACK_DEV }}
            echo "Start"
            # php artisan down
            sh deploy.sh -dev
            # php artisan up
            echo "Finish"
